### ISSUE TITLE
Problem starting the server

### ISSUE THREAD

**Issue by 22karthik** [fdietz/recipes-with-angular-js-examples#18]
app.configure(function(){
    ^

TypeError: app.configure is not a function
    at Object.<anonymous> (E:\Nodejs\recipes-with-angular-js-examples-master\recipes-with-angular-js-examples-master\chapter10\recipe1\contacts\app.js:7:5)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Function.Module.runMain (module.js:682:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3

**Comment by 22karthik** [comment]
Hi upon starting the server node app.js I get the above error.

**Comment by theangular** [comment]
test

**Comment by theangular** [comment]
test

**Comment by theangular** [comment]
test

**Comment by theangular** [comment]
test1

**Comment by theangular** [comment]
test2
