### ISSUE TITLE
Please Update examples with latest version of Angular JS

### ISSUE THREAD

**Issue by Mazzzy** [fdietz/recipes-with-angular-js-examples#9]
The examples are according to angular version for years 2010-2012. Please update it so that the examples will work with latest version without any error.

**Comment by Zifah** [comment]
Hello Mazzy,

I was recently trying to use the examples too and ran into errors.

Could you help with information on how the error:

 Error: [ng:areq] http://errors.angularjs.org/1.3.0/ng/areq?p0=MyCtrl&p1=not%20a%20function%2C%20got%20undefined
    at Error (native)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.3.0/angular.min.js:6:416
    at Mb (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.0/angular.min.js:19:510)
    at nb (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.0/angular.min.js:20:78)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.3.0/angular.min.js:74:494
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.3.0/angular.min.js:56:415
    at r (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.0/angular.min.js:7:408)
    at M (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.0/angular.min.js:56:281)
    at g (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.0/angular.min.js:51:201)
    at g (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.0/angular.min.js:51:218)angular.js:11358 (anonymous function)

for more recent version of angular was resolved?

This particular error is in Chapter 1, Recipe 3

**Comment by bilw** [comment]
This is a more recent approach to the app.js file.

var app = angular.module('myApp', []);
app.controller('myCtrl', function($scope){
  $scope.visible = true;

  $scope.toggle = function(){
    $scope.visible = !$scope.visible;
  };
});
